name: SayHello

on:
 push:
   branches:
     - develop
     - main
    
jobs:
  welcome:
     runs-on: ubuntu-latest
     
     steps:
       - name: Download your code ðŸ“¬ â¬‡
         uses: actions/checkout@v2

       - name: Say something ðŸ“£
         run: echo "hello world"
       
  hello-branches:
      runs-on: ubuntu-latest

      steps:
       - name: Download your code ðŸ“¬ â¬‡
         uses: actions/checkout@v2
   
       - name: Verify develop branch ðŸ””
         if: ${{ github.ref == 'refs/heads/develop'}}
         run: echo "hello develop"

       - name: Verify main develop ðŸ””
         if: ${{ github.ref == 'refs/heads/main'}}
         run: echo "hello main"

         


      
